set ::env(DESIGN_NAME) "silicon_npu"
set ::env(VERILOG_FILES) "/workspace/flow/src/silicon_npu.sv"
set ::env(CLOCK_PERIOD) "20.0"
set ::env(CLOCK_PORT) "clk"
set ::env(CLOCK_NET) "clk"
set ::env(PDK) "sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SYNTH_DRIVING_CELL) "sky130_fd_sc_hd__inv_2"
set ::env(MAX_FANOUT_CONSTRAINT) 6
set ::env(FP_CORE_UTIL) 50
set ::env(FP_ASPECT_RATIO) 1
set ::env(PL_TARGET_DENSITY) 0.6
set ::env(GRT_REPAIR_ANTENNAS) 1
set ::env(DIODE_ON_PORTS) "in"
set ::env(RUN_HEURISTIC_DIODE_INSERTION) 1
set ::env(QUIT_ON_TIMING_VIOLATIONS) "false"
set ::env(RUN_KLAYOUT) "0"
set ::env(RUN_LINTER) "0"
